package DivideConquer;

public class Mergesort {


    public static void printarr(int arr[]){
        for (Object elem : arr) {
                System.out.println(elem);
        }
    }

    public static void mergesort(int arr[] ,int si , int ei) {
        int mid = si+(ei-si)/2;
        mergesort(arr, si, mid);
        mergesort(arr, ei, mid+1);
        merge(arr, si,ei, mid);
    }
    public static void merge(int arr[] ,int si ,int ei ,int mid) {
        int temp[] = {};
        if(si)
    }
    public static void main(String[] args) {
        int arr[] = {2,1,3,4,6,5};
        Mergesort ms = new Mergesort();
        // ms.mergesort(arr,0,arr.length-1);
        ms.printarr(arr);
    }
}



// DHURANDHARDHURANDHAR           DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR  DHURANDHARDHURANDHARDHURANDHAR  DHURANDHARDHURANDHARDHURANDHAR  DHURANDHARDHURANDHARDHURANDHAR DHURANDHARDHURANDHAR           DHURANDHAR          DHURANDHAR DHURANDHARDHURANDHARDHURANDHAR DHURANDHARDHURANDHARDHURANDHAR
// DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR  DHURANDHARDHURANDHARDHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR         ZDHURANDHAR
// DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR         ZDHURANDHAR
// DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR         ZDHURANDHAR
// DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR         ZDHURANDHAR
// DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR  DHURANDHARDHURANDHARDHURANDHAR  DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHARDHURANDHARDHURANDHAR
// DHURANDHAR          DHURANDHAR DHURANDHARDHURANDHARDHURANDHAR DHURANDHAR          DHURANDHAR  DHURANDHAR DHURANDHAR           DHURANDHARDHURANDHARDHURANDHAR  DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHARDHURANDHARDHURANDHAR DHURANDHARDHURANDHARDHURANDHAR DHURANDHARDHURANDHAR
// DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR  DHURANDHAR   DHURANDHAR         DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR  DHURANDHAR
// DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR  DHURANDHAR      DHURANDHAR      DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR    DHURANDHAR
// DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR  DHURANDHAR        DHURANDHAR    DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR      DHURANDHAR
// DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR        DHURANDHAR
// DHURANDHARDHURANDHAR           DHURANDHAR          DHURANDHAR DHURANDHARDHURANDHARDHURANDHAR  DHURANDHAR           DHURANDHAR DHURANDHAR          DHURANDHAR  DHURANDHAR          DHURANDHAR DHURANDHARDHURANDHAR           DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR DHURANDHAR          DHURANDHAR
